# Generated by Django 4.0.7 on 2022-10-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='Brand_offer',
            field=models.IntegerField(default=0),
        ),
    ]
