# Generated by Django 4.0.7 on 2022-10-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_product_offer_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
    ]
