# Generated by Django 4.0.7 on 2022-10-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
