# Generated by Django 4.0.7 on 2022-10-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='wishList',
        ),
    ]
