# Generated by Django 4.0.7 on 2022-10-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_wishlistitem_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='wishlistitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.wishlistitem'),
        ),
    ]
