# Generated by Django 4.0.7 on 2022-10-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cartitem_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='wishlistitem',
        ),
    ]
