# Generated by Django 4.0.7 on 2022-10-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_category_offer'),
        ('orders', '0002_productoffer_categoryoffer_brandoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category'),
        ),
    ]
