# Generated by Django 4.0.7 on 2022-10-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_productoffer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.FloatField(default=0),
        ),
    ]
